### ISSUE TITLE
Missing Windows Package

### ISSUE THREAD

**Issue by davewalter** [bosh-packages/cf-cli-release#4]
Hi CF CLI Team,

The `cf-cli-6-windows` package is missing from the release. We currently package this into the [cf-smoke-tests-release](https://github.com/cloudfoundry/cf-smoke-tests-release/tree/master/packages/cf_cli_windows), but it would be great if it could be included here so that we can rely on a colocated `cf-cli-release` instead, just as we do for Linux.

Thanks in advance,
Dave

cc @vitreuz @Changdrew @acosta11 @Syerram

**Comment by acrmp** [comment]
Placeholder story in tracker here:
https://www.pivotaltracker.com/story/show/167111311

**Comment by genevieve** [comment]
On the garden windows team, we are looking to use the cf-cli as part of two bosh releases (hwc-offline-buildpack-release and windows-stacks-release.) They both have cf-cli packages with different versions but due to the naming, we are seeing collision fails at deploy time. If we could have both releases point to a colocated cf-cli-release with a cf-cli that works on windows, that would be ideal.
